[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = [ "tpknam1qzlgemrrn3y385av6fccqd680jxvzxmaqlfp60vhteqqlfznc7sxz4lf6w0",]

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = [ "tpknam1qq2u0jtkn2vyvnfzg4xva5m5a22m37gph26puqef5szu9fmu83ppkmd0e7h",]

[[validator_account]]
address = "tnam1qxkvz9k38ay9av947auh0mrg7q7kr985gur07h73"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:29657"

[validator_account.consensus_key]
pk = "tpknam1qzavyfea6lrn50cdt8umv74yy5eaj60efvpp5u4srjw04fs7prwecgvz0f9"
authorization = "signam1qqt22chh9lyaklskaq8wesuvz9mq62d8gju09sh9zw2fqumewvnuc7zqxesrpewxp7f20gzzcrugalw98e6f68kzdkwt2qexz0spp0s8fjnued"
[validator_account.protocol_key]
pk = "tpknam1qrry30avjmu4rgjsg6j7f344l7w8aaqxzd7vwmhmswtarljcdehwy4gmr3y"
authorization = "signam1qz46q40v6v69y2tq6n78mnxcm0wrstgkemwr9lgj5wqr3tqzhtwf5k9g6glakcgejm8d5wur7wphjtw35dqdgk0c5zel7ntxk6vapgqxsvh94d"
[validator_account.tendermint_node_key]
pk = "tpknam1qqwyjvrgfa6u07f44mhesft209dhaem0mfs76n4tmyykulurp2mpsvwz6h3"
authorization = "signam1qq9k88f58f88wctm8dk7tvzf4p4k343hkelgxruyxfn68qz7xd5wfwt086w0m653karhsaru3n82lvewssr05jvl2mskghjfyrsxpqq07a6jz4"
[validator_account.eth_hot_key]
pk = "tpknam1qypvu5004awnrlq06pfdffj8sfyqcyx7dkhd4r9nfpudsqxrltttajq9yran6"
authorization = "signam1qymctfd2jnxwqfl5qz35kvuyahwy3s9p0c4jnssepyvzfqfzqxfjuraluzv6jr7hrg0pjau9v80ufzkw8xjdk9s76w3s6w05khwk6pl9qym5pd5n"
[validator_account.eth_cold_key]
pk = "tpknam1qypp7sctufg2xkpjrh8ce9tcxw5tv8gmy4eqvk86e4exrnadnmlfnxsj5tafa"
authorization = "signam1q9cru7axw025u6gya68a6q3378k77qv5wqvt3k5ke7l77g3kjqnnsl9a55a49jeypscffff5jxc63yh02q548qqp2t6rcetergjvy87cqyah3lh3"
[validator_account.metadata]
email = "validator2@gmail.com"
[validator_account.signatures]
tpknam1qzlgemrrn3y385av6fccqd680jxvzxmaqlfp60vhteqqlfznc7sxz4lf6w0 = "signam1qrmedf8n5w3s6lrtenlllcltzm8srf3dnc6wdzwfm80a279fgvps7yhjkyf0mfdwtcn3806tul4f6x9hnare8sefrs4p0lc74ty0rwsp3tryj6"
[[validator_account]]
address = "tnam1qxx7e820zrulmmzex9lldz5nn9x9edp93cyfpz5k"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:28657"

[validator_account.consensus_key]
pk = "tpknam1qrkuyzmc2p34pr6s6efqexzz6zr6vu08m32g4wla7kdaylfw5j88clg0nfq"
authorization = "signam1qz449z4ajgj74ns0t95x8t7wt0nnpmcqwq6dd6nrhqatvrflpy9p7txxc9w9umjtxhv2kqy9xjssjhennt5n464qqal6m5f65y8nuwgxv44cd8"
[validator_account.protocol_key]
pk = "tpknam1qr0hu60njx7577vcpwahl9v5vlfve8mh2n20e758w76qc79qa7hhgz8xxmp"
authorization = "signam1qrhfzf7a8ddn5pdhmvcqfzzp6gwy3flhmpfrrnplw7kyed6ech24u8y3g49ykpgr837qen8ezqvvujehmh8mnyyhergpkv3ndq56xfqdk84pte"
[validator_account.tendermint_node_key]
pk = "tpknam1qz5n5rga6l7g9gznsv48p5hf9swqcqgmqr3kyh3cuk5vk6wf74u8cld5c4a"
authorization = "signam1qzmpd5dcct6gp85ms7k4w94pm66can2ym20l27uyrr535c0q5z70uk72vs8fy8jlne6cm096tg89a8lwzn4nn8429vqy6qnfhvsmr2qy8hf9wg"
[validator_account.eth_hot_key]
pk = "tpknam1qypn600cl0tkdwf094k6m0e2zpsxskhmt05pg3cjmxg7e8a9zdy7z9qjpj57j"
authorization = "signam1q9x9whvck2uexg6tr7l4k4vdxj0hcj6tpuv4l8t0qdmw2sddh599k6fgpuaua5633v4jgutuvz7qdvzmlxxxnuyy9zmr2f467vprh2e7qqt359pa"
[validator_account.eth_cold_key]
pk = "tpknam1qyptdu9r0d047xl5r5h7t282ergjzm8ecq4qtp4z5awd243tlhwezjcd39m4s"
authorization = "signam1qyvsz0t4ww6e900k7yuy2gr2q9drjurmcn0h44u2whv5c0fnwmw7u36lept6l2pzun44xvmru5ps63me9crxe07y8v5ddl9jj6fnxhveqq56h25z"
[validator_account.metadata]
email = "validator1@gmail.com"
[validator_account.signatures]
tpknam1qq2u0jtkn2vyvnfzg4xva5m5a22m37gph26puqef5szu9fmu83ppkmd0e7h = "signam1qqwdfm356fed2u08x6xfypfgc058g6ymlrmy7uyjvxswaumwm046crs0ua6wque2hxxp976dzqcddqpw65txlywkwwzfdnja7ttm5jqws7325v"
[[bond]]
source = "tnam1qxkvz9k38ay9av947auh0mrg7q7kr985gur07h73"
validator = "tnam1qxkvz9k38ay9av947auh0mrg7q7kr985gur07h73"
amount = "1000"

[bond.signatures]
tpknam1qzlgemrrn3y385av6fccqd680jxvzxmaqlfp60vhteqqlfznc7sxz4lf6w0 = "signam1qpxyetwn2jsmg0yuzautrrmg3efgxl0e3tj73erpznvuzxavlnwfwghxyhug9wdxq23v5hznpkcpqm5fhce0lgd9v9629x9dtgpj6ysv7g267a"
[[bond]]
source = "tnam1qxx7e820zrulmmzex9lldz5nn9x9edp93cyfpz5k"
validator = "tnam1qxx7e820zrulmmzex9lldz5nn9x9edp93cyfpz5k"
amount = "1000"

[bond.signatures]
tpknam1qq2u0jtkn2vyvnfzg4xva5m5a22m37gph26puqef5szu9fmu83ppkmd0e7h = "signam1qrr6sa5krqvfg06u4cm83eh45j776t46k9cxulu49zzrcudxfy4kyvst309nfvwtp7240cpq6dlx47w8eshkx6765mcdfk4l25eyp5cgemylxl"
