[package]
authors = ["Heliax <TODO@heliax.dev>"]
edition = "2018"
name = "Anoma data template"
version = "0.1.0"

[lib]
name = "anoma_data_template"
path = "src/lib.rs"

[dependencies]
borsh = "0.8.2"
bytes = "1.0.1"
