---
kind: pipeline
type: docker
name: anoma-ci-build-pr

workspace:
  path: /drone/workspace

environment:
  CARGO_HOME: /drone/workspace/.cargo
  RUSTUP_HOME: /drone/workspace/.rustup
  GIT_LFS_SKIP_SMUDGE: "1"

steps:
  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      cache_key: "{{ checksum \"Cargo.lock\" }}"
      archive_format: "gzip"
      mount:
        - .cargo
        - matchmaker_template/target
        - txs/tx_from_intent/target
        - txs/tx_template/target
        - txs/tx_transfer/target
        - vps/vp_template/target
        - vps/vp_token/target
        - vps/vp_user/target
        - txs/tx_update_vp
        - filter_template
        - target
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key

  - name: build
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
    pull: if-not-exists
    commands:
      - make -C txs/tx_template deps
      - make build-wasm-scripts
      - make build
    depends_on:
      - restore-cache

  - name: test
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
    pull: if-not-exists
    commands:
      - make test
    depends_on:
      - build

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "{{ checksum \"Cargo.lock\" }}"
      mount:
        - .cargo
        - matchmaker_template/target
        - txs/tx_from_intent/target
        - txs/tx_template/target
        - txs/tx_transfer/target
        - vps/vp_template/target
        - vps/vp_token/target
        - vps/vp_user/target
        - txs/tx_update_vp
        - filter_template
        - target
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      BACKEND_OPERATION_TIMEOUT: "8m"
    when:
      status:
        - success
        - failure
    depends_on:
      - test

trigger:
  event:
    - pull_request

node:
  project: anoma

---
kind: pipeline
type: docker
name: anoma-ci-checks-pr

workspace:
  path: /drone/workspace

environment:
  CARGO_HOME: /drone/workspace/.cargo
  RUSTUP_HOME: /drone/workspace/.rustup
  GIT_LFS_SKIP_SMUDGE: "1"

steps:
  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      cache_key: "nightly/{{ checksum \"Cargo.lock\" }}"
      archive_format: "gzip"
      mount:
        - .cargo
        - target
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key

  - name: clippy-fmt-checks
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
    pull: if-not-exists
    commands:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - . /drone/workspace/.cargo/env
      - make dev-deps
      - make clippy-check
      - make fmt-check
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "nightly/{{ checksum \"Cargo.lock\" }}"
      mount:
        - .cargo
        - target
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      BACKEND_OPERATION_TIMEOUT: "8m"
    when:
      status:
        - success
        - failure
    depends_on:
      - clippy-fmt-checks
  
trigger:
  event:
    - pull_request

node:
  project: anoma

---
kind: pipeline
type: docker
name: anoma-ci-audit-pr

workspace:
  path: /drone/workspace

environment:
  CARGO_HOME: /drone/workspace/.cargo
  RUSTUP_HOME: /drone/workspace/.rustup
  GIT_LFS_SKIP_SMUDGE: "1"

steps:
  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      cache_key: "audit/{{ checksum \"Cargo.lock\" }}"
      archive_format: "gzip"
      mount:
        - .cargo
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key

  - name: audit
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
    pull: if-not-exists
    commands:
      - cargo install cargo-audit
      - make audit
    depends_on:
      - restore-cache

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "audit/{{ checksum \"Cargo.lock\" }}"
      mount:
        - .cargo
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      BACKEND_OPERATION_TIMEOUT: "8m"
    when:
      status:
        - success
        - failure
    depends_on:
      - audit
  
trigger:
  event:
    - pull_request

node:
  project: anoma

---
kind: pipeline
type: docker
name: anoma-ci-build-master-develop

workspace:
  path: /drone/workspace

environment:
  CARGO_HOME: /drone/workspace/.cargo
  RUSTUP_HOME: /drone/workspace/.rustup
  GIT_LFS_SKIP_SMUDGE: "1"

steps:
  - name: restore-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      restore: true
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      cache_key: "{{ checksum \"Cargo.lock\" }}"
      archive_format: "gzip"
      mount:
        - .cargo
        - matchmaker_template/target
        - txs/tx_from_intent/target
        - txs/tx_template/target
        - txs/tx_transfer/target
        - vps/vp_template/target
        - vps/vp_token/target
        - vps/vp_user/target
        - txs/tx_update_vp
        - filter_template
        - target
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key

  - name: build
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
    pull: if-not-exists
    commands:
      - make -C txs/tx_template deps
      - make build-wasm-scripts
      - make build
    depends_on:
      - restore-cache

  - name: test
    image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
    pull: if-not-exists
    commands:
      - make test
    depends_on:
      - build

  - name: rebuild-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    settings:
      backend: "s3"
      bucket: heliax-drone-cache-v2
      region: eu-west-1
      rebuild: true
      archive_format: "gzip"
      override: false
      cache_key: "{{ checksum \"Cargo.lock\" }}"
      mount:
        - .cargo
        - matchmaker_template/target
        - txs/tx_from_intent/target
        - txs/tx_template/target
        - txs/tx_transfer/target
        - vps/vp_template/target
        - vps/vp_token/target
        - vps/vp_user/target
        - txs/tx_update_vp
        - filter_template
        - target
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
      BACKEND_OPERATION_TIMEOUT: "8m"
    when:
      status:
        - success
        - failure
    depends_on:
      - test
  
trigger:
  event:
    - push
  branch:
    - develop
    - master

node:
  project: anoma
---
kind: signature
hmac: 9d6cfb1ad004ffc28aa80e630385746abb53a25804f6570a9ffb04d9a06be32e

...
