---
environment: {CARGO_HOME: /usr/local/rust/project/.cargo, CARGO_INCREMENTAL: 0, GIT_LFS_SKIP_SMUDGE: '1'}
kind: pipeline
name: anoma-ci-build-pr
node: {project: anoma}
steps:
- commands: [echo "f8d0b0b96f7100565e1f5bf93982da152688417fbfdb801d91c72e9232f7dd5f  Makefile"
      | sha256sum -c -, echo "6ff9ee796028a3cc674c5234487a6438c44994af4bae458302c4ff2bd75199a8  vps/vp_template/Makefile"
      | sha256sum -c -, echo "e5e1c98a178c66f170acea2094a0a71536f68e806ced68930658e284976b9241  vps/vp_token/Makefile"
      | sha256sum -c -, echo "23e0790dc5d81059c121b1d0cef3c294aec09e1ae2b1a2252f20ae1d0051417f  vps/vp_user/Makefile"
      | sha256sum -c -, echo "56bbb4a6c96a48e7be40c98f2c7e674c0580e6e5d3caa0316e64bb6c5be20aa4  txs/tx_template/Makefile"
      | sha256sum -c -, echo "8155f89cd64ca742ef48dfd24fe4144be2edc8d8d8019f6dc0379b0d59f355ac  txs/tx_transfer/Makefile"
      | sha256sum -c -, echo "f98eadb24cc100740298fe20636c9c7faf7232437587285dc02609992961f0db  txs/tx_from_intent/Makefile"
      | sha256sum -c -, echo "d3e31e26868d9f54577491332e6cd182d357a242fcef487dd63505a7fb7b4574  txs/tx_update_vp/Makefile"
      | sha256sum -c -, echo "1a434407b45351e0f4a8bb83654e1c098eb35de444fdec2f2083cc682e9785c9  matchmaker_template/Makefile"
      | sha256sum -c -, echo "8f3e68c0447731b7fc2027084920ada9e5c671d7e0b58ed907e07b49c9972189  filter_template/Makefile"
      | sha256sum -c -]
  image: alpine/git:v2.30.1
  name: check-scripts-integrity
  pull: if-not-exists
- depends_on: [check-scripts-integrity]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
  image: meltwater/drone-cache
  name: restore-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: '{{ checksum "Cargo.lock" }}'
    mount: [.cargo]
    region: eu-west-1
    restore: true
- commands: [sccache --start-server, make -C txs/tx_template deps, make build-wasm-scripts,
    "for wasm in $(ls filter_template/*.wasm matchmaker_template/*.wasm txs/*/*.wasm
      vps/*/*.wasm)\ndo\n  shasum -a 256 ${wasm} >> checksum.sha256\ndone\n", make
      clean-wasm-scripts, make build-wasm-scripts, shasum -c checksum.sha256, rm checksum.sha256]
  depends_on: [restore-cache]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    SCCACHE_BUCKET: heliax-drone-cache-v2
    SCCACHE_S3_KEY_PREFIX: sccache-build-wasm
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: build-wasm
  pull: if-not-exists
- commands: [sccache --start-server, make build]
  depends_on: [build-wasm]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    SCCACHE_BUCKET: heliax-drone-cache-v2
    SCCACHE_S3_KEY_PREFIX: sccache-build
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: build
  pull: if-not-exists
- commands: [sccache --start-server, make test]
  depends_on: [build]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    SCCACHE_BUCKET: heliax-drone-cache-v2
    SCCACHE_S3_KEY_PREFIX: sccache-test
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: test
  pull: if-not-exists
- commands: [cargo-cache]
  depends_on: [test]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: clean-cache
  pull: if-not-exists
- depends_on: [clean-cache]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    BACKEND_OPERATION_TIMEOUT: 8m
  image: meltwater/drone-cache
  name: rebuild-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: '{{ checksum "Cargo.lock" }}'
    mount: [.cargo]
    override: false
    rebuild: true
    region: eu-west-1
  when:
    status: [success, failure]
trigger:
  branch: [develop, master]
  event: [pull_request, push]
type: docker
workspace: {path: /usr/local/rust/project}
---
environment: {CARGO_HOME: /usr/local/rust/project/.cargo, CARGO_INCREMENTAL: 0, GIT_LFS_SKIP_SMUDGE: '1'}
kind: pipeline
name: anoma-ci-checks-pr
node: {project: anoma}
steps:
- commands: [echo "f8d0b0b96f7100565e1f5bf93982da152688417fbfdb801d91c72e9232f7dd5f  Makefile"
      | sha256sum -c -, echo "6ff9ee796028a3cc674c5234487a6438c44994af4bae458302c4ff2bd75199a8  vps/vp_template/Makefile"
      | sha256sum -c -, echo "e5e1c98a178c66f170acea2094a0a71536f68e806ced68930658e284976b9241  vps/vp_token/Makefile"
      | sha256sum -c -, echo "23e0790dc5d81059c121b1d0cef3c294aec09e1ae2b1a2252f20ae1d0051417f  vps/vp_user/Makefile"
      | sha256sum -c -, echo "56bbb4a6c96a48e7be40c98f2c7e674c0580e6e5d3caa0316e64bb6c5be20aa4  txs/tx_template/Makefile"
      | sha256sum -c -, echo "8155f89cd64ca742ef48dfd24fe4144be2edc8d8d8019f6dc0379b0d59f355ac  txs/tx_transfer/Makefile"
      | sha256sum -c -, echo "f98eadb24cc100740298fe20636c9c7faf7232437587285dc02609992961f0db  txs/tx_from_intent/Makefile"
      | sha256sum -c -, echo "d3e31e26868d9f54577491332e6cd182d357a242fcef487dd63505a7fb7b4574  txs/tx_update_vp/Makefile"
      | sha256sum -c -, echo "1a434407b45351e0f4a8bb83654e1c098eb35de444fdec2f2083cc682e9785c9  matchmaker_template/Makefile"
      | sha256sum -c -, echo "8f3e68c0447731b7fc2027084920ada9e5c671d7e0b58ed907e07b49c9972189  filter_template/Makefile"
      | sha256sum -c -]
  image: alpine/git:v2.30.1
  name: check-scripts-integrity
  pull: if-not-exists
- depends_on: [check-scripts-integrity]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
  image: meltwater/drone-cache
  name: restore-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: nightly/{{ checksum "Cargo.lock" }}
    mount: [.cargo]
    region: eu-west-1
    restore: true
- commands: [sccache --start-server, make clippy-check]
  depends_on: [restore-cache]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    SCCACHE_BUCKET: heliax-drone-cache-v2
    SCCACHE_S3_KEY_PREFIX: sccache-check
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: clippy-check
  pull: if-not-exists
- commands: [sccache --start-server, make fmt-check]
  depends_on: [restore-cache]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    SCCACHE_BUCKET: heliax-drone-cache-v2
    SCCACHE_S3_KEY_PREFIX: sccache-check
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: fmt-check
  pull: if-not-exists
- commands: [cargo-cache]
  depends_on: [clippy-check, fmt-check]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: clean-cache
  pull: if-not-exists
- depends_on: [clean-cache]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    BACKEND_OPERATION_TIMEOUT: 8m
  image: meltwater/drone-cache
  name: rebuild-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: nightly/{{ checksum "Cargo.lock" }}
    mount: [.cargo]
    override: false
    rebuild: true
    region: eu-west-1
  when:
    status: [success, failure]
trigger:
  branch: [develop, master]
  event: [pull_request, push]
type: docker
workspace: {path: /usr/local/rust/project}
---
environment: {CARGO_HOME: /usr/local/rust/project/.cargo, CARGO_INCREMENTAL: 0, GIT_LFS_SKIP_SMUDGE: '1'}
kind: pipeline
name: anoma-ci-audit-pr
node: {project: anoma}
steps:
- commands: [echo "f8d0b0b96f7100565e1f5bf93982da152688417fbfdb801d91c72e9232f7dd5f  Makefile"
      | sha256sum -c -, echo "6ff9ee796028a3cc674c5234487a6438c44994af4bae458302c4ff2bd75199a8  vps/vp_template/Makefile"
      | sha256sum -c -, echo "e5e1c98a178c66f170acea2094a0a71536f68e806ced68930658e284976b9241  vps/vp_token/Makefile"
      | sha256sum -c -, echo "23e0790dc5d81059c121b1d0cef3c294aec09e1ae2b1a2252f20ae1d0051417f  vps/vp_user/Makefile"
      | sha256sum -c -, echo "56bbb4a6c96a48e7be40c98f2c7e674c0580e6e5d3caa0316e64bb6c5be20aa4  txs/tx_template/Makefile"
      | sha256sum -c -, echo "8155f89cd64ca742ef48dfd24fe4144be2edc8d8d8019f6dc0379b0d59f355ac  txs/tx_transfer/Makefile"
      | sha256sum -c -, echo "f98eadb24cc100740298fe20636c9c7faf7232437587285dc02609992961f0db  txs/tx_from_intent/Makefile"
      | sha256sum -c -, echo "d3e31e26868d9f54577491332e6cd182d357a242fcef487dd63505a7fb7b4574  txs/tx_update_vp/Makefile"
      | sha256sum -c -, echo "1a434407b45351e0f4a8bb83654e1c098eb35de444fdec2f2083cc682e9785c9  matchmaker_template/Makefile"
      | sha256sum -c -, echo "8f3e68c0447731b7fc2027084920ada9e5c671d7e0b58ed907e07b49c9972189  filter_template/Makefile"
      | sha256sum -c -]
  image: alpine/git:v2.30.1
  name: check-scripts-integrity
  pull: if-not-exists
- depends_on: [check-scripts-integrity]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
  image: meltwater/drone-cache
  name: restore-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: audit/{{ checksum "Cargo.lock" }}
    mount: [.cargo]
    region: eu-west-1
    restore: true
- commands: [make audit]
  depends_on: [restore-cache]
  image: 965844283396.dkr.ecr.eu-west-1.amazonaws.com/anoma:latest
  name: audit
  pull: if-not-exists
- depends_on: [restore-cache]
  environment:
    AWS_ACCESS_KEY_ID: {from_secret: aws_access_key_id}
    AWS_SECRET_ACCESS_KEY: {from_secret: aws_secret_access_key}
    BACKEND_OPERATION_TIMEOUT: 8m
  image: meltwater/drone-cache
  name: rebuild-cache
  pull: if-not-exists
  settings:
    archive_format: gzip
    backend: s3
    bucket: heliax-drone-cache-v2
    cache_key: audit/{{ checksum "Cargo.lock" }}
    mount: [.cargo]
    override: false
    rebuild: true
    region: eu-west-1
  when:
    status: [success, failure]
trigger:
  branch: [develop, master]
  event: [pull_request, push]
type: docker
workspace: {path: /drone/workspace}
---
kind: signature
hmac: fa25be65c3e58c67dfc3bd151752240491bd4e669a96179536cca2a6fbcb5f1e

...
