allow-branch               = ["main", "maint-*"]
consolidate-commits        = true
pre-release-commit-message = "Namada {{version}}"
publish                    = false
push                       = false
shared-version             = true
sign-tag                   = true
tag-message                = "Namada {{version}}"
tag-name                   = "v{{version}}"
