[[validator_account]]
alias = "validator-0"
dkg_key = "dpknam1vqqqqqqndwmp3cvzfuepzvdh3fmt4dvjwd4vx6ffxk6t4vm6waysng2q8zh3yu8hdnxhwnwq22p8fwaqlyzcggef6k6qv3h3qtyy8c8c686w50v7d0z49ufd6zje46ujzc4ew5z7sdh45d94cvywy2v40yz9jlck3p6lxe"
vp = "vp_validator"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:27656"

[validator_account.account_key]
pk = "tpknam1qpqznlesv6fcgsz9x4rsn7l4dsnp7h5sswvs9atw0zgq3uwp0jll2fh8yx5"
authorization = "signam1qrcy6a095uj6n8ryc9fkfw3hn2jn285g82hdratzrvmg22xp5qdmyr7e9q97t77v4zr8a73x4c3k53pcec3mp4ugt5jqd2w0fvd7nhcpw8587v"

[validator_account.consensus_key]
pk = "tpknam1qpk2a5m26cgnrp32l2c2hss03draxwnctu92llhlr6kjesn2kt892ugmzmh"
authorization = "signam1qzajuey408zf66wgw8x3awd5jx9x249csx63n80clehj238qqpsf9cdr630edqjr8fw95vywlngy368r087sge2xy89qpcsrxvwtm3grwdulku"

[validator_account.protocol_key]
pk = "tpknam1qpfv9pj4zmelcg98rtw8wezztzdgpuczuxjmx946klkxajmvvcxjzmwac78"
authorization = "signam1qz0aerskgtzwmgxwgml72zyz4974njfz6s9dl7r399d0v64pzsmctkwe8f28dwyef52hklj6r2fqmeypncvv3qg2x4hg4u3g23kw23qtlt64na"

[validator_account.tendermint_node_key]
pk = "tpknam1qp7shxxfdkp8ft8xfkgf2vqy7u6effdp82w0cq6aq8575txul33t6m0fe73"
authorization = "signam1qq87l6zjuswmrfeysxp8j0tu5zlklnswzaqgcuyaq23p49hhvupa57r3rwrh3txfuvq8lh5e7wu7d90js8cn7a7dygs7v5yx2a9ljtqx09f0l6"

[validator_account.eth_hot_key]
pk = "tpknam1qypdzza7uqtklzzs50hhy07h5ru9p0v8y5666wwulqnd3mdpuj0tcxstywa2d"
authorization = "signam1q9qtzvwlqhnft5jgeyms2w757dlly8rjg4g89593ayhan0fx7uvjzvm7r7ltgsly9tp6783pqpl6ezxty240udrrknxmunymz6lm523qqqlu57sc"

[validator_account.eth_cold_key]
pk = "tpknam1qypzca0n6l890jc83nk5lljuzps04xmfccz3f87xc6ez40t2wvql48shkqpgm"
authorization = "signam1q8qmjstc2jtt3dwueepv0njk9te5qpj6z9yj6w0duhagswz80vyws3ywdsy9n49qnjecvnpxwlna3578vn423tgd4rrtss06ejgkj7c5qyasq8gl"

[[transfer]]
token = "nam"
source = "tpknam1qzp22w6trhmxmp2dx5h883c2l684z0e20a9egusmxaat62wvaa4agjf64ch"
target = "validator-0"
amount = "200000"
signature = "signam1qz8ch7n6jp7g7hvnzkhmprhqc5umd0gatarlttm7gpcdx6g8hmgqffdq67fn6vzcflmym5xej3m5jmfw7nap00s4nlx2zxrlwz0wlfgt3lswty"

[[bond]]
source = "validator-0"
validator = "validator-0"
amount = "100000"
signature = "signam1qpss2x7vewnr2sr2wxj0ftldcmvv7v7t7qsr26k2l2hx4gls7y9sksrcq0m9vv2ymdqqxgmmw0dmuwazflxuqt4v2p2wng4endtcfcc0dq0drt"
