[[validator_account]]
alias = "validator-0"
dkg_key = "dpktest1vqqqqqphsfm2hwzpxnkmf3kzcyq3ps2kxjqmk2sresfn8mwas4vysrluu0smn3mlpsshyv0ex49u8n2nm5gpk87unxlzczfvhac2x4malhhr3wwyvhuu3uwgd66jgvkg463h86eywphupgwawnus23vgnats3mvw56as6v"
vp = "vp_validator"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
email = "null@null.net"
net_address = "127.0.0.1:27656"

[validator_account.account_key]
pk = "pktest1qzfc6ytsytksl8spkzmqlhmmanf7rnkqta4u3sp87ldakj3a5l2svfea2qn"
authorization = "sigtest1qrj64httssprssqhhra9668kxlus8muqjef3p20dcuah2vmctkevy7dxysheelt3ng4mdwzytu7405u6mz54w8pj4kg76cvx4hl8l7qv5j8avl"

[validator_account.consensus_key]
pk = "pktest1qr7783f60w4shwlcuz44qcswzzxzpfyren6kzx36dyctds7lkg97g3zprnd"
authorization = "sigtest1qqlr2j7qvxrp7hnjs6hxpxd8zgk7xpatplrll3wcpj62tqymvvzty86x3rkrhygczmmkcqssvvtx7m0x9x7qvh3806hcakr4f2zug0cw8qfnjr"

[validator_account.protocol_key]
pk = "pktest1qpd3wf3e4j9ms6an68894qu23tz5clwxcg7uknm5tvdspxeep609x24s9wm"
authorization = "sigtest1qpnzlq4lsa7z22gu5nmdyfx09cn78l4a8k0w04d8adhlekl007s8exjmznxm4kxry6u7ep6un8fkz0vqlvh5xt3h3cf7690kmst8r4srmyw8m7"

[validator_account.tendermint_node_key]
pk = "pktest1qzew97uet42t6v74u4vkdhsvhhul874a32rrv6jyaf3tlqnje9dmsqpj8yf"
authorization = "sigtest1qpgmdf8r5sdl9l8yljqw9hvhyvkww3zurd72xcr88sl5qxamduwmdufrq8attgypl254fdvqcnt9rnv064x5c2dgxtcm675wph9umqc8ht6gv8"

[validator_account.eth_hot_key]
pk = "pktest1qypl23ydd0l2gcykw9g0juxyycx5l84zr2m4dnw08pepnslllyl4zfqf6ay24"
authorization = "sigtest1qx563nytyc58xj422y83n7fhxyc73szxsgdgw90zhptqgajl09s8g08knz2uv80eagpar04aswdmpkxulp8tz6n8kmtk87jwxrm3v2wdqy8vtat8"

[validator_account.eth_cold_key]
pk = "pktest1qyp5ng08ttca26aapu9vwrkjcwfhkncqmdd7lkwxa6wsd892yea5jtc5pqjfw"
authorization = "sigtest1qy5n259562ehv82h9ajyfa94gm85zdyds9jhjf5f6gczsp0rgmtps0q6pm3755thne700lc24pr5mjz6muc5sexlvk45s8z5rcr2leqdqqcj5u4r"

[[transfer]]
token = "nam"
source = "pktest1qzp22w6trhmxmp2dx5h883c2l684z0e20a9egusmxaat62wvaa4agcthpup"
target = "validator-0"
amount = "200000"
signature = "sigtest1qz8ch7n6jp7g7hvnzkhmprhqc5umd0gatarlttm7gpcdx6g8hmgqffdq67fn6vzcflmym5xej3m5jmfw7nap00s4nlx2zxrlwz0wlfgts9kera"

[[bond]]
source = "validator-0"
validator = "validator-0"
amount = "100000"
signature = "sigtest1qpfa9tn8wgnfcvafdqu3u7pq0gmfyavsuwc0en533z0kakm9jpks00ns5wrl5g30s6mxxllv94wm86vph4hcp0ztxxe4aw2npcz56lg2eygu4q"
