[[validator_account]]
alias = "validator-0"
vp = "vp_validator"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:27656"

[validator_account.account_key]
pk = "pktest1qqsw3u3agvmg2c9e3xtcea9przvrv3ndcxqz8k6vffe8gj9nplpkgqaamdn"
authorization = "sigtest1qqry4m7jyhyatcs4kk48cj3hk7qksxw4nsjzl5vc8sa7aytk9y8nvq4r40q5vhju6nd4svvk459ce0dslwmhxuga2683lh44xfc52csy877897"

[validator_account.consensus_key]
pk = "pktest1qrrz2h24kph8c4pt8httuna8ktwpw5cwf4uja853g3dge6teutr3quv2kgf"
authorization = "sigtest1qq32d722qk72459uyc2stdf0q2suctrr2psnf4kqvm9tms2d7d8da4tgpswzutxwp2433swv2rc7lx4y7fz53tavyxw5xwa4jjfpeqcgdyukh2"

[validator_account.protocol_key]
pk = "pktest1qqd4xuedcmll27jhsqtltcmtjynfa0q7lh3x8jdxgxd3apkawhnyxm3gtkg"
authorization = "sigtest1qze9vtf8ec3qyhssfwankah3mk2a0sg8mwzqegdd735rl2fz9y0a5n98l59g398smqy3ln6vqw9xsuletrqx32gch022y49czqnql2cyu863t5"

[validator_account.tendermint_node_key]
pk = "pktest1qqg430t7lv4tpzktgqw7z260me2lcq50q7a5nhgvafd7q83jz488jzt4jud"
authorization = "sigtest1qr0vkj47fkvz2562nv2emyp7svsrwckq5kdhx9t6p2m0lcscg390ad55vu437qu9hnv6mmj443xl4pyqpzgxt6083whxk2xa7zxsaucwcmy0e6"

[validator_account.eth_hot_key]
pk = "pktest1qyp85qem385et2q7hq2upawpjh2jz34nkx3dx58rqgtfz9m0dhzsphckk70f5"
authorization = "sigtest1qxr8z29e30m8qk7ttc87lzsz52s7al203qupn8qqnnwrgmh26w7yze87gjpkfappucjwaxl5msr37m6pplhfk8rfypfecmnjvhxa0ffrqqhlnu4p"

[validator_account.eth_cold_key]
pk = "pktest1qypa8zltua2anpwuh2llk0s4l4s8sme02lewtkyc67a5lknsyk4uqvg37r34q"
authorization = "sigtest1q9m9sknufmhgs5s9kj40tzqch2n2ffw3r8n9827xk7s3tc449xsuykrqh0txtazz2862uvmjygqy77zfr7qz0maqvek0tdjs07prl2m0qqkuztl2"

[[transfer]]
token = "nam"
source = "pktest1qzp22w6trhmxmp2dx5h883c2l684z0e20a9egusmxaat62wvaa4agcthpup"
target = "validator-0"
amount = "200000"
signature = "sigtest1qz8ch7n6jp7g7hvnzkhmprhqc5umd0gatarlttm7gpcdx6g8hmgqffdq67fn6vzcflmym5xej3m5jmfw7nap00s4nlx2zxrlwz0wlfgts9kera"

[[bond]]
source = "validator-0"
validator = "validator-0"
amount = "100000"
signature = "sigtest1qrd0rmfpxwppgtys30sj8xu03p6dr3vpc250ly3ex4j86m884snneeequhyttuvqre8hj8pnds62uu6n7u2d4vajzd0f4u30wrvvyqgtkld6vs"
