[parameters]
native_token = "NAAN"
min_num_of_blocks = 30
max_expected_time_per_block = 20
max_tx_bytes = 1048576
max_proposal_bytes = 6291456
vp_allowlist = []
tx_allowlist = []
implicit_vp = "vp_implicit"
epochs_per_year = 250000
max_signatures_per_transaction = 15
max_block_gas = 5000000
fee_unshielding_gas_limit = 20000
fee_unshielding_descriptions_limit = 15

[pos_params]
max_validator_slots = 257
pipeline_len = 2
unbonding_len = 4
tm_votes_per_token = "1"
block_proposer_reward = "0.125"
block_vote_reward = "0.1"
max_inflation_rate = "0.0"
target_staked_ratio = "0.0"
duplicate_vote_min_slash_rate = "0.001"
light_client_attack_min_slash_rate = "0.001"
cubic_slashing_window_length = 1
validator_stake_threshold = "1000000000"
liveness_window_check = 8640
liveness_threshold = "0.9"
rewards_gain_p = "0.0"
rewards_gain_d = "0.0"

[gov_params]
min_proposal_fund = 5000
max_proposal_code_size = 600000
min_proposal_voting_period = 2
max_proposal_period = 6
max_proposal_content_size = 10000
min_proposal_grace_epochs = 2

[pgf_params]
stewards = []
pgf_inflation_rate = "0.0"
stewards_inflation_rate = "0.0"

[parameters.minimum_gas_price]
naan = "0.0001"
