# Transactions pasted from:
#
# 1. `src/pre-genesis/validator-0/transactions.toml`
# 2. `src/pre-genesis/signed-transactions.toml`

# 1.

[[validator_account]]
alias = "validator-0"
dkg_key = "dpktest1vqqqqqphsfm2hwzpxnkmf3kzcyq3ps2kxjqmk2sresfn8mwas4vysrluu0smn3mlpsshyv0ex49u8n2nm5gpk87unxlzczfvhac2x4malhhr3wwyvhuu3uwgd66jgvkg463h86eywphupgwawnus23vgnats3mvw56as6v"
vp = "vp_validator"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
email = "null@null.net"
net_address = "127.0.0.1:27656"

[validator_account.account_key]
pk = "pktest1qzfc6ytsytksl8spkzmqlhmmanf7rnkqta4u3sp87ldakj3a5l2svfea2qn"
authorization = "sigtest1qrj64httssprssqhhra9668kxlus8muqjef3p20dcuah2vmctkevy7dxysheelt3ng4mdwzytu7405u6mz54w8pj4kg76cvx4hl8l7qv5j8avl"

[validator_account.consensus_key]
pk = "pktest1qr7783f60w4shwlcuz44qcswzzxzpfyren6kzx36dyctds7lkg97g3zprnd"
authorization = "sigtest1qqlr2j7qvxrp7hnjs6hxpxd8zgk7xpatplrll3wcpj62tqymvvzty86x3rkrhygczmmkcqssvvtx7m0x9x7qvh3806hcakr4f2zug0cw8qfnjr"

[validator_account.protocol_key]
pk = "pktest1qpd3wf3e4j9ms6an68894qu23tz5clwxcg7uknm5tvdspxeep609x24s9wm"
authorization = "sigtest1qpnzlq4lsa7z22gu5nmdyfx09cn78l4a8k0w04d8adhlekl007s8exjmznxm4kxry6u7ep6un8fkz0vqlvh5xt3h3cf7690kmst8r4srmyw8m7"

[validator_account.tendermint_node_key]
pk = "pktest1qzew97uet42t6v74u4vkdhsvhhul874a32rrv6jyaf3tlqnje9dmsqpj8yf"
authorization = "sigtest1qpgmdf8r5sdl9l8yljqw9hvhyvkww3zurd72xcr88sl5qxamduwmdufrq8attgypl254fdvqcnt9rnv064x5c2dgxtcm675wph9umqc8ht6gv8"

[validator_account.eth_hot_key]
pk = "pktest1qypl23ydd0l2gcykw9g0juxyycx5l84zr2m4dnw08pepnslllyl4zfqf6ay24"
authorization = "sigtest1qx563nytyc58xj422y83n7fhxyc73szxsgdgw90zhptqgajl09s8g08knz2uv80eagpar04aswdmpkxulp8tz6n8kmtk87jwxrm3v2wdqy8vtat8"

[validator_account.eth_cold_key]
pk = "pktest1qyp5ng08ttca26aapu9vwrkjcwfhkncqmdd7lkwxa6wsd892yea5jtc5pqjfw"
authorization = "sigtest1qy5n259562ehv82h9ajyfa94gm85zdyds9jhjf5f6gczsp0rgmtps0q6pm3755thne700lc24pr5mjz6muc5sexlvk45s8z5rcr2leqdqqcj5u4r"

[[transfer]]
token = "nam"
source = "pktest1qzp22w6trhmxmp2dx5h883c2l684z0e20a9egusmxaat62wvaa4agcthpup"
target = "validator-0"
amount = "200000"
signature = "sigtest1qz8ch7n6jp7g7hvnzkhmprhqc5umd0gatarlttm7gpcdx6g8hmgqffdq67fn6vzcflmym5xej3m5jmfw7nap00s4nlx2zxrlwz0wlfgts9kera"

[[bond]]
source = "validator-0"
validator = "validator-0"
amount = "100000"
signature = "sigtest1qpfa9tn8wgnfcvafdqu3u7pq0gmfyavsuwc0en533z0kakm9jpks00ns5wrl5g30s6mxxllv94wm86vph4hcp0ztxxe4aw2npcz56lg2eygu4q"

# 2.

[[established_account]]
alias = "albert"
vp = "vp_user"

[established_account.public_key]
pk = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
authorization = "sigtest1qzq6dwf2a9dq4hp3nmxfgckh55mulzryxsfkqhr9uvfvmtr9wt38lyyvzvfqryxnat2a4ry6hygv957z683dyngu03gse2uvl5ldfccypktkp6"

[established_account.storage]

[[established_account]]
alias = "bertha"
vp = "vp_user"

[established_account.public_key]
pk = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
authorization = "sigtest1qzt58nd7k2mj647x8x4ydhsjkut7dmsl7yjlnrnwu9kzjdch3cljv6dq05mx2kvwn80kjezh7lz26adc5ksvyn3knufymtkhlmnhg3c8zka3y4"

[established_account.storage]

[[established_account]]
alias = "christel"
vp = "vp_user"

[established_account.public_key]
pk = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
authorization = "sigtest1qrf2l6a5u4ywskryhdueudnm50j3kqhujas3mmktenqm89fmlskjnyeskr2tr7js5swmtqqtenkj6ap9xpelx2w40fjjczc4w9xtdggqjtszy4"

[established_account.storage]

[[transfer]]
token = "nam"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qrxfthuz5yzapdt82d8nc656ffrzkxnkfg6fw8w7e6045vcpn8kpr4c536ug4fs2ddz5823dfd3w4qnhcl40qmtasfccaa99a0hvjcqvyy2l02"

[[transfer]]
token = "btc"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qq826qel8zn5p4dfx25ma45uxeskx0yjlsaxp38uyvehvds6t93c8wkhaydunm4nzz9750dwhkjst00mfrwmu066y3rj6gtk5wjskxq9zvk7ed"

[[transfer]]
token = "eth"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qzghddk0u6kpqaxhskrj8ah69d3hce95wndgvlpuyvuw0h0fnyrnp026ltvtfmfhpzywkf88yyhv80hzkus57s9nn6vn3ljvmkkf7zgq2nzn40"

[[transfer]]
token = "dot"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qqlu8kajh0up5zhewd2h44fhq7zdaapqt9xaj8xp7jmdqpv4dl9d5tesw3wyr9su962rvpkf02x27579vqjk4f4advx7t9ejz74cjrc25puna6"

[[transfer]]
token = "schnitzel"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qpukdd6f7pvtgau9v58xxwrnmv5pjra6527aggce9j8cu6fnekzag2cmmf4w0x0cn76gpth2vw6zcsnw37xjuz96hflqfnk5sznxe6cfd5mjnv"

[[transfer]]
token = "apfel"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qprnsyhlruvw4a6jjs98xdd04gxdsgycywzt79gyyak68gn4f50ppdvdm0q6ns44cheu7s43kal0qsldml8s0zexqk3s9zmglu4l6fszwcqswy"

[[transfer]]
token = "kartoffel"
source = "pktest1qz0aphcsrw37j8fy742cjwhphu9jwx7esd3ad4xxtxrkwv07ff63wnnul44"
target = "albert"
amount = "1000000"
signature = "sigtest1qpg4y6ltax3qfclguym2kpa0ezlkf4hz4u3h8fc2ndmuzm4zfe26ygq9u6nhjjvj93n5v296x4arkvjk22ygee2fx054ce7ap6gvynq2j2k0vf"

[[transfer]]
token = "nam"
source = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
target = "bertha"
amount = "1000000"
signature = "sigtest1qpe3ms76cxvqsa58624ked5ndjr3jr3u7lf9ypalxdh29gajwmsxtzjxzswk0xmza90u47tgksr0d7enpd730ps7fq5u76l7ekxeyvgfnl0qxj"

[[transfer]]
token = "btc"
source = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
target = "bertha"
amount = "1000000"
signature = "sigtest1qqq4yc6s3h4ysezcmgsdgyfsqu8mmrwwc8a358sm864zehx74ums8fmgmkyyr3wz9qqrc5fagwrw0a4mgqkkleumc0u6ynshj5ns0tcdrygupg"

[[transfer]]
token = "eth"
source = "pktest1qpyfnrl6qdqvguah9kknvp9t6ajcrec7fge56pcgaa655zkua3ndsl9tn4a"
target = "bertha"
amount = "1000000"
signature = "sigtest1qzyqkdxt3cxf0huv0hzskqmuthw38s3kj2sx50znzc68gzx64hrd3hkyx0g27pruwa9fv42suw3k8gkfaelcp4ymnvfw7ltx0mz2z9qr2lwwcs"

[[transfer]]
token = "nam"
source = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
target = "christel"
amount = "1000000"
signature = "sigtest1qran2jh0dwuwchh45snhk3p9uyxqym57eg527pcjeekwhvpr5j0fy6dte7x3v2dwwc6vqmv49drpvmk6uhzlt2p8rqx0th3h7smf8rqrcpfxc7"

[[transfer]]
token = "btc"
source = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
target = "christel"
amount = "1000000"
signature = "sigtest1qrxp6p56qtvsyp7jfs4jru3mkfv6l4t7hpguur72579pqjaexdry9turgmzwzj6qmua3s2y2a4krtuxwaag66j4dpz44aaqksy30tfcxmnhw2k"

[[transfer]]
token = "eth"
source = "pktest1qp6uy52q0fldjxupznuskm69fkuswx3fq3vw9kekzp4enkh5h7pmzy242c2"
target = "christel"
amount = "1000000"
signature = "sigtest1qrtrec6mps9p7zhmm7sywxwc7zdm32umt0zdwpuflrkh6952rx74amnsf9hn0yughs4e6czgpdmwsmujvkr4ptk2x24vtc8phz0s2asvtyy9pf"

[[bond]]
source = "albert"
validator = "validator-0"
amount = "20000"
signature = "sigtest1qpx0kc8rl966vnnswfwhcwxh5vv69p7lev2apc2yephag978gqg5903kuw6dugg9c6pg5jdw048umk72ntympphz0dka74aspldslaqr3q7eqr"
