# Transactions pasted from:
#
# 1. `src/pre-genesis/validator-0/transactions.toml`
# 2. `src/pre-genesis/signed-transactions.toml`

# 1.

[[validator_account]]
vp = "vp_validator"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
email = "null@null.net"
net_address = "127.0.0.1:27656"

[validator_account.account_key]
pk = "tpknam1qpzrttnzfyt6xfu2vy092eruasll3z52rjfexwapdw0rdww5uktlk3j73dw"
authorization = "signam1qpacfs9vhfmng7kg4mwv5w5erpx0aep6ttlss8fp7lywk5tdylprd5lwjtcntdpkj2f0sv86jh8yqk9yz3htzgf49806tpxekmm7zvcvx5zwrc"

[validator_account.consensus_key]
pk = "tpknam1qrh65c7f0v7czem4mzmene8alcut27sud6w9n5xpasklweq48rk3kxj5jqz"
authorization = "signam1qpqc3pgxr4vrjejl4jgdqqrf7qlguha2qttzsy9m6h90td5elqcl3u8xdu5zg2awrz8wfpuxkcsgrgtx9s2ttkjv33syexx73879zes9fl8u6l"

[validator_account.protocol_key]
pk = "tpknam1qz7pxp8xn5evxkkglzfgnwnepppzugvvzgzkjtk4r7mk4kk7cl8qzl0djvm"
authorization = "signam1qr3c4ffk5v4a8ghwenrc6lzegefas20nw5n0ua0hjzru7vjarkfphgrkhrr62jpq2yjnq3npdjx9xs62cdmeqz5sa0sfzg242vk37vgdh4uskx"

[validator_account.tendermint_node_key]
pk = "tpknam1qq86kujgcx26w54qnled9cdvxn6u2jyfmpluaajfm5g67w748xg0qtgwqwg"
authorization = "signam1qq46hmyr4a535la3fh7gyuq9uc3t3f5lmzauy3qykej5amye904ya8dp9telpew0nn4m5lfrqy0jet24qhu7jve8nzq65acymdv7phcdhgr842"

[validator_account.eth_hot_key]
pk = "tpknam1qypr03729ez4ms2cmqajy4r8t09ljg98k9u6vfv7zxyz6c3y4mn8uws2flwkm"
authorization = "signam1qykjcjy046u0hs0ghlf90afq26p6de65rllfu29kd354yzhpc0dksnaxqjh0a6sjzwv56txd666uwfdx2w9pkr7rzxrrr0naxk3gxp6sqqqsgh4c"

[validator_account.eth_cold_key]
pk = "tpknam1qypmnl7euqn0ej0tcdg4l9u5khmxzryy3dsdqyfl34hfqkgufehxugcj9uc9x"
authorization = "signam1q97m2g3uvgtausnq3vdjd4sg5f7mz8pktfta5czgv6p0yz63ahwa7tvmef79ne6z9u8vj0637hrasv7ud3534c8wr744ge6q9ztf84gyqy3lzywq"

[[bond]]
source = "tnam1qyfcx4un953sf06lhcja377hk2z6faw67ykx549w"
validator = "tnam1qyfcx4un953sf06lhcja377hk2z6faw67ykx549w"
amount = "100000"
signature = "signam1qrzvengdrngds8rz9qj0m5mze2afd5mev479nadnx3gq2alcnxyx59eyxk2q0kc0qv9w6936fmgvq0snu0yx7lfpes9akw2txrjsxqsvwc6xwz"

# 2.

[[established_account]]
vp = "vp_user"

[established_account.public_key]
pk = "tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha"
authorization = "signam1qz39jpapmmxyc99ra8ty74kdx8c0kax3n42z7n5y44e3tcara4ezm3l4llgwgqhp0kgg0kz48d02v2xfeqn5at4h069dddvmlhral7qgm59d37"

[[established_account]]
vp = "vp_user"

[established_account.public_key]
pk = "tpknam1qq52dx5e290wyh7ngdt6wudtyd502lg6ln49yvg3vz97e8j2ruux5e3yewq"
authorization = "signam1qqqvnh3e3j8rv6au622yw74jj76wpty7pttlnfussnyffhg8sk07q7g5ehw5hyz67amnvr4afmcr6tcfs6ktylcqrtc0h350j4zd0qgpqwn9z7"

[[established_account]]
vp = "vp_user"

[established_account.public_key]
pk = "tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"
authorization = "signam1qqfsz9dvtsan6kqp8zn256gvnuw5hsr27935w63cu0hl30535ewx7tpsf3zypq0hxmjh23z4q4sk7l046n6gjqmvg9ueyxl69lxgzvcfvujj9x"

[[bond]]
source = "tnam1q8uthkc42sw609e8ce6tcjwu6mgz6zgtccff8wdt"
validator = "tnam1qyfcx4un953sf06lhcja377hk2z6faw67ykx549w"
amount = "20000"
signature = "signam1qz00emwjxmvgjlknc55qffxepur6xlay4zhmnejchw32nuwz2kajmn06hdkmdctu9nrnp3kk0hg6495rsvm5paglyuvyekzcvcxzp2qxvf8hlh"
