[workspace]
resolver = "2"

members = [
    "wasm_source",
    "tx_template",
    "vp_template",
]

[patch.crates-io]
# TODO temp patch for <https://github.com/near/borsh-rs/issues/82>, <https://github.com/near/borsh-rs/issues/84> and more tba.
borsh = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
borsh-schema-derive-internal = {git = "https://github.com/heliaxdev/borsh-rs.git", rev = "cd5223e5103c4f139e0c54cf8259b7ec5ec4073a"}
# patched to a commit on the `eth-bridge-integration+consensus-timeout` branch of our fork
tendermint = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "cf4dd4ccb64c12485ff764c10888237cf87396bc"}
tendermint-config = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "cf4dd4ccb64c12485ff764c10888237cf87396bc"}
tendermint-proto = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "cf4dd4ccb64c12485ff764c10888237cf87396bc"}
tendermint-rpc = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "cf4dd4ccb64c12485ff764c10888237cf87396bc"}
tendermint-testgen = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "cf4dd4ccb64c12485ff764c10888237cf87396bc"}
tendermint-light-client-verifier = {git = "https://github.com/heliaxdev/tendermint-rs.git", rev = "cf4dd4ccb64c12485ff764c10888237cf87396bc"}

# patched to a commit on the `eth-bridge-integration` branch of our fork
ibc = {git = "https://github.com/heliaxdev/cosmos-ibc-rs.git", rev = "17c6d16e6e32c5db96f1d9026ce6beb019cdc7c4"}
ibc-proto = {git = "https://github.com/heliaxdev/ibc-proto-rs.git", rev = "e50ec3c3c1a9a0bcc3cd59516645ff5b4e1db281"}

[profile.release]
# smaller and faster wasm (https://rustwasm.github.io/book/reference/code-size.html#compiling-with-link-time-optimizations-lto)
lto = true
# simply terminate on panics, no unwinding
panic = "abort"
# tell llvm to optimize for size (https://rustwasm.github.io/book/reference/code-size.html#tell-llvm-to-optimize-for-size-instead-of-speed)
opt-level = 'z'
