[package]
name = "anoma"
version = "0.1.0"
authors = ["Heliax <TODO@heliax.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
abci = "0.7.1"
byteorder = "1.4.2"
log = "0.4.14"
env_logger = "0.8.2"