genesis_time = "2021-12-20T15:00:00.00Z"
native_token = "NAM"
faucet_pow_difficulty = 0
faucet_withdrawal_limit = "1000"

[parameters]
min_num_of_blocks = 5
max_expected_time_per_block = 11
implicit_vp = "vp_implicit"
epochs_per_year = 210240000
pos_gain_p = 0.1
pos_gain_d = 0.1
wrapper_tx_fees = "5"
max_proposal_bytes = 5242880
vp_whitelist = []
tx_whitelist = []
max_public_key_per_account = 15
max_signature_per_tx = 15

[pos_params]
max_validator_slots = 128
pipeline_len = 2
unbonding_len = 4
tm_votes_per_token = 0.1
block_proposer_reward = 0.125
block_vote_reward = 0.1
max_inflation_rate = 0.1
target_staked_ratio = 0.6667
duplicate_vote_min_slash_rate = 0.001
light_client_attack_min_slash_rate = 0.001

[gov_params]
min_proposal_fund = 100
max_proposal_code_size = 300000
min_proposal_period = 3
max_proposal_period = 6
max_proposal_content_size = 10000
min_proposal_grace_epochs = 0

[pgf_params]
stewards = []
payments = []
pgf_inflation_rate = 0.05
stewards_inflation_rate = 0.01

[token.NAM]
address = "atest1v4ehgw36x3prswzxggunzv6pxqmnvdj9xvcyzvpsggeyvs3cg9qnywf589qnwvfsg5erg3fkl09rg5"
vp = "vp_token"

[token.BTC]
address = "atest1v4ehgw36xdzryve5gsc52veeg5cnsv2yx5eygvp38qcrvd29xy6rys6p8yc5xvp4xfpy2v694wgwcp"
vp = "vp_token"

[token.ETH]
address = "atest1v4ehgw36xqmr2d3nx3ryvd2xxgmrq33j8qcns33sxezrgv6zxdzrydjrxveygd2yxumrsdpsf9jc2p"
vp = "vp_token"

[token.DOT]
address = "atest1v4ehgw36gg6nvs2zgfpyxsfjgc65yv6pxy6nwwfsxgungdzrggeyzv35gveyxsjyxymyz335hur2jn"
vp = "vp_token"

[token.Schnitzel]
address = "atest1v4ehgw36xue5xvf5xvuyzvpjx5un2v3k8qeyvd3cxdqns32p89rrxd6xx9zngvpegccnzs699rdnnt"
vp = "vp_token"

[token.Apfel]
address = "atest1v4ehgw36gfryydj9g3p5zv3kg9znyd358ycnzsfcggc5gvecgc6ygs2rxv6ry3zpg4zrwdfeumqcz9"
vp = "vp_token"

[token.Kartoffel]
address = "atest1v4ehgw36gep5ysecxq6nyv3jg3zygv3e89qn2vp48pryxsf4xpznvve5gvmy23fs89pryvf5a6ht90"
public_key = ""
vp = "vp_token"

[established.faucet]
address = "atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3"
vp = "vp_testnet_faucet"

[established.masp]
address = "atest1v4ehgw36xaryysfsx5unvve4g5my2vjz89p52sjxxgenzd348yuyyv3hg3pnjs35g5unvde4ca36y5"
vp = "vp_masp"

[wasm.vp_implicit]
filename = "vp_implicit.wasm"

[wasm.vp_user]
filename = "vp_user.wasm"

[wasm.vp_validator]
filename = "vp_validator.wasm"

[wasm.vp_token]
filename = "vp_token.wasm"

[wasm.vp_testnet_faucet]
filename = "vp_testnet_faucet.wasm"

[wasm.vp_masp]
filename = "vp_masp.wasm"

[validator.validator-local-dev]
consensus_public_key = "00a49e322f10f2ded221b51953cd355e50451c8c0b65a2ad5e7b3fae5376363c5f"
account_public_key = "009d73e6bc4e6c27e33ee04c3eadb1e563ab1e5bff82362c1f3081775aa45a51ab"
protocol_public_key = "00bd7ac86c4f93b08141967d021350549dee8ec64edd0e9a736f1d84e21dad5f12"
dkg_public_key = "60000000773997304c9348bd7fd25db77c0810e9f29f76e13a39dfabfe6a94e4c8355bcdbd63444b5b6f62f0f50a0dca9403ba081cce888307ee557ff411eb9fc51b58c25c31dba549cdd8bd6c898357508d450c792f7e40b662e627f921becce39f7b18"
commission_rate = "0.1"
max_commission_rate_change = "0.1"
net_address = "127.0.0.1:26656"
tendermint_node_key = "0037714cd1cf90f7be465cefb5c36d67f14af0d90aab186979cfc4029b12d6997d"
tokens = 6714000000
non_staked_balance = 1000000000000
validator_vp = "vp_user"
staking_reward_vp = "vp_user"

[token.NAM.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.BTC.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.ETH.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.DOT.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.Schnitzel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.Apfel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

[token.Kartoffel.balances]
atest1v4ehgw36gc6yxvpjxccyzvphxycrxw2xxsuyydesxgcnjs3cg9znwv3cxgmnj32yxy6rssf5tcqjm3 = 9223372036854

