[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = [ "tpknam1qphc07ccm0043eyd2jsjq83985vuhm6k8j5wlndrg2lnla5rkr605qquv6l",]

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = [ "tpknam1qpwjvh7td87q44cs78c0uluwl7tq2ljxkeyudunc4uqq3tj38gx8jms4kws",]

[[validator_account]]
address = "tnam1qyqxdjexcs8lpr24r6u96e4387rfa4zzsu7vvymm"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:29657"

[validator_account.consensus_key]
pk = "tpknam1qqx2w0e0rasplx0tpdhg4ssmfn4y8h78czjk6wg0dsmc8s38rxz360xeau7"
authorization = "signam1qragypl8kuccy978amksthcqqx9krsrr563zrcy6w65r8sgqekqmgdk6pn4rptqt2q40q7d7g36fnr9yynh4j5t5gxdc7n45n9qf84cx9rtdy4"
[validator_account.protocol_key]
pk = "tpknam1qq0lajrdkc2vw0vcnzq4zg0jv82gw7jmqmhc805p32wa49tf8rx4700hfrd"
authorization = "signam1qqumkwser0nz8rqqtawfsaaq6rp2law2am6pka48rflghfj92fvknhut3fjuxnvms9hwj0cs7lxawt7w9w55ufdaw5ku0g0g3rg7qdqf23mqes"
[validator_account.tendermint_node_key]
pk = "tpknam1qrkys8zgzas5nfwghchay6gv2kqjcgwhdm324p9wz66cj7dgx4rkxt0ej7a"
authorization = "signam1qqk0el92ch8uclx7tl87sj3kq9s4vaglfhuwzfm3g8rlp37tcxhts3taptqw0n759zp4dsjkwfuxg9lgpdzr2839nzz4l6upjcz7v7gw5nwc0l"
[validator_account.eth_hot_key]
pk = "tpknam1qyp0hn4345844py3jr2nauu525gns780rm4jfx9wmhfq20w7qu7u5wsag84dw"
authorization = "signam1qykmtszg8kpm95hh53mzlddylfkhacp09avd79r5t5whj3lyemdy78gp9nzy0js2g8aqq37m65ns0nv98tafpfe7gugxsrpxvz7luqrsqy3ls6ql"
[validator_account.eth_cold_key]
pk = "tpknam1qyp99zaaza25j6yq9yrxu657ayy5qfwma3qat4gdemnrwhj0mdegkgq4fa4yn"
authorization = "signam1q9mdlvxm0qdsf5nxkcxfu3nccyfq2985g9rgxpweh3emln5w0s8kgvefvgaafc4kv27j20ex3frp7vjscjjm850kg5wcdgakl4ddsdguqq9658lz"
[validator_account.metadata]
email = "validator2@gmail.com"
[validator_account.signatures]
tpknam1qphc07ccm0043eyd2jsjq83985vuhm6k8j5wlndrg2lnla5rkr605qquv6l = "signam1qr7y9ynv2eyd2s80rvv2ppktees0xzflk84n7ccyx0r7skhnqamkr0xacxzucgw0heahuluregsklev97k7k5khc8a0nnsc92r7t7nqtq8uc2a"
[[validator_account]]
address = "tnam1q8378h06dkpdzq9krsrs3sw7lcxfmery4y6g8udy"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:28657"

[validator_account.consensus_key]
pk = "tpknam1qpggrw92cey8rtwcm59zpe557t2n9wzzxwn4fd9hz4fpsqt65lrggmpk2qm"
authorization = "signam1qpecgu48md0lj0usqr0yrxkmm2pr0vpchamy6hsmyklfv4v3snn6w7c43n75tyfn8ltg88z5ex5c403dqzrn85vkhn0hyjzdhym0p0gy7yuxqt"
[validator_account.protocol_key]
pk = "tpknam1qzv7x635yhfrvp339j30myxz8vsvrn4qg0zpdg0280z4uuqmvc85jgfu2kf"
authorization = "signam1qzvawyh2d84vwmna7sm48heres4d7vquz0yanpvehstwwcemvm5mggg6ndagupduq39vkwxuu0c7kj4wzhzpnc3z8ny9vc3ly3glacsg28gn9a"
[validator_account.tendermint_node_key]
pk = "tpknam1qqttqvf6ruaf5zeelvc7cltgyzcjm2yamtlxcedp7vumxugmsnmhv2f9e0j"
authorization = "signam1qp7drqzqd5zevddyzwrh5ydnqmd2pwre6rqxn42mv4d53sec23a8prkpqykxass5ma3ntnsuemzwp60ck4ertq4zraynfkkk7eqs3ycvtw3efy"
[validator_account.eth_hot_key]
pk = "tpknam1qyp06r4hq40qs0ashkw9qpq23kfkcdc6nulwwuh8cwfumht2syzy6eqrujn75"
authorization = "signam1q8c76g9gqgzrk0r88dhvytkrzlfgm3p7q7wul0u8vagehf6uzx94kpwgc026mn5mmetadunlu2z2sn5amkyd85t58ce4pl30q8vpyyyzqqtvr3dr"
[validator_account.eth_cold_key]
pk = "tpknam1qyp3r6dpwtw8emker7u979ks556w9rdmyc337lkur0kah2nru8zud9gpr9prr"
authorization = "signam1q88mndk940w2eg4l9mlkes3tvcv9cww68f5kkvf3m928qlz7wm7evjqjevg7fttyd3czraemxe3g325fqjkwlcc7wkck5n0kym7ugv6pqq00f0zs"
[validator_account.metadata]
email = "validator1@gmail.com"
[validator_account.signatures]
tpknam1qpwjvh7td87q44cs78c0uluwl7tq2ljxkeyudunc4uqq3tj38gx8jms4kws = "signam1qz9aejpjzzcwfkypx357d08k69v4pzscuqqygmkz9q7k7596lvryrncc8nex7fraz9cgnerlmr46s2eevtdcat2600jfjrg07cm7k8s0cysvxr"
[[bond]]
source = "tnam1qyqxdjexcs8lpr24r6u96e4387rfa4zzsu7vvymm"
validator = "tnam1qyqxdjexcs8lpr24r6u96e4387rfa4zzsu7vvymm"
amount = "1000"

[bond.signatures]
tpknam1qphc07ccm0043eyd2jsjq83985vuhm6k8j5wlndrg2lnla5rkr605qquv6l = "signam1qzlc39amzcl573wmmyh0q6tdrkrurj342zevunt639k9tql3w939ll7jwgfxxwtnh2zp22d5gqga22nvqnqsc5u5gepl4hx8v2hpntcrqs0hx0"
[[bond]]
source = "tnam1q8378h06dkpdzq9krsrs3sw7lcxfmery4y6g8udy"
validator = "tnam1q8378h06dkpdzq9krsrs3sw7lcxfmery4y6g8udy"
amount = "1000"

[bond.signatures]
tpknam1qpwjvh7td87q44cs78c0uluwl7tq2ljxkeyudunc4uqq3tj38gx8jms4kws = "signam1qrlf5kfe5qrtu0nzef5c2sz4ra3vm28lzjrhnk9uqdwmvaa2gl0ajv4w5tr5c0ckfzd55f9rka5hre7857scemyy9xp80feygppp4sgxqv924z"
