[[established_account]]
vp = "vp_user"

[established_account.public_key]
pk = "tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha"
authorization = "signam1qz39jpapmmxyc99ra8ty74kdx8c0kax3n42z7n5y44e3tcara4ezm3l4llgwgqhp0kgg0kz48d02v2xfeqn5at4h069dddvmlhral7qgm59d37"

[[established_account]]
vp = "vp_user"

[established_account.public_key]
pk = "tpknam1qq52dx5e290wyh7ngdt6wudtyd502lg6ln49yvg3vz97e8j2ruux5e3yewq"
authorization = "signam1qqqvnh3e3j8rv6au622yw74jj76wpty7pttlnfussnyffhg8sk07q7g5ehw5hyz67amnvr4afmcr6tcfs6ktylcqrtc0h350j4zd0qgpqwn9z7"

[[established_account]]
vp = "vp_user"

[established_account.public_key]
pk = "tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"
authorization = "signam1qqfsz9dvtsan6kqp8zn256gvnuw5hsr27935w63cu0hl30535ewx7tpsf3zypq0hxmjh23z4q4sk7l046n6gjqmvg9ueyxl69lxgzvcfvujj9x"

[[bond]]
source = "tnam1q8uthkc42sw609e8ce6tcjwu6mgz6zgtccff8wdt"
validator = "tnam1qyfcx4un953sf06lhcja377hk2z6faw67ykx549w"
amount = "20000"
signature = "signam1qz00emwjxmvgjlknc55qffxepur6xlay4zhmnejchw32nuwz2kajmn06hdkmdctu9nrnp3kk0hg6495rsvm5paglyuvyekzcvcxzp2qxvf8hlh"
