[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = [ "tpknam1qqw7lpnxmcfdws069z0x8m2ufrjz0udagt9yh0vhgyy8ks2k97qxxg883yz",]

[[validator_account]]
address = "tnam1q87tthcxzszsz9vznu3fj394kzxqkq8jzcnagg2y"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:28657"
consensus_key = "tpknam1qrcysztkpe802s58a6sszkj7dc37kte50v28x0hcgmfsutzwn8x5c8kkkyg"
protocol_key = "tpknam1qp4407l30rvavayt3n87k0374gc0y4fgghge7q5mwezznnje246k20urdqf"
tendermint_node_key = "tpknam1qpsj3qrk7vknq95j64pvnw0kjg0wash9ncvmgk56wn857czmwrc728vefma"
eth_hot_key = "tpknam1qypgyqugjftv9gjd7veh7aljvlzntndlxzmt3l9tyz7nc5cavg5fuscts7q7c"
eth_cold_key = "tpknam1qype9a65xvd2920y37w8u96dh0fsepgy3cj7va33kg552m0cvhtdfsq5wq6av"

[validator_account.metadata]
email = "validator1@gmail.com"
[[bond]]
source = "tnam1q87tthcxzszsz9vznu3fj394kzxqkq8jzcnagg2y"
validator = "tnam1q87tthcxzszsz9vznu3fj394kzxqkq8jzcnagg2y"
amount = "1000"

