# This file contains hand-written unsigned transactions for localnet with:
#
# - MASP account
# - Faucet account that allows anyone to withdraw limited amount of tokens
# - 2 established accounts for "Albert" and "Bertha"
#
# Note that 2 more localnet user accounts "Christel" and "Daewon" are left as
# implicit accounts, so their tokens are kept in the accounts derived from their
# keys used in `balances.toml`.
#
# This file is used to produce `signed-transactions.toml` with
# the `sign-genesis-tx` command.

# Albert
[[established_account]]
vp = "vp_user"
public_key = "tpknam1qrnw8mxyqlj60mykgevnldcj5mg2fya7fs5a8xqdkd2gwtxhef0zy8a2wha"

# Bertha
[[established_account]]
vp = "vp_user"
public_key = "tpknam1qq52dx5e290wyh7ngdt6wudtyd502lg6ln49yvg3vz97e8j2ruux5e3yewq"

# Christel
[[established_account]]
vp = "vp_user"
public_key = "tpknam1qqwfpuvn8x7yqtquejhppef4vddv9ghusec2rkaxav38amamxaxpgj9cs79"

##########################################################################################

# Albert bonds to `validator-0`
[[bond]]
source = "tnam1q8uthkc42sw609e8ce6tcjwu6mgz6zgtccff8wdt"
validator = "tnam1qyfcx4un953sf06lhcja377hk2z6faw67ykx549w"
amount = "20000"
