[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = [ "tpknam1qphc07ccm0043eyd2jsjq83985vuhm6k8j5wlndrg2lnla5rkr605qquv6l",]

[[established_account]]
vp = "vp_user"
threshold = 1
public_keys = [ "tpknam1qpwjvh7td87q44cs78c0uluwl7tq2ljxkeyudunc4uqq3tj38gx8jms4kws",]

[[validator_account]]
address = "tnam1qyqxdjexcs8lpr24r6u96e4387rfa4zzsu7vvymm"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:29657"
consensus_key = "tpknam1qqx2w0e0rasplx0tpdhg4ssmfn4y8h78czjk6wg0dsmc8s38rxz360xeau7"
protocol_key = "tpknam1qq0lajrdkc2vw0vcnzq4zg0jv82gw7jmqmhc805p32wa49tf8rx4700hfrd"
tendermint_node_key = "tpknam1qrkys8zgzas5nfwghchay6gv2kqjcgwhdm324p9wz66cj7dgx4rkxt0ej7a"
eth_hot_key = "tpknam1qyp0hn4345844py3jr2nauu525gns780rm4jfx9wmhfq20w7qu7u5wsag84dw"
eth_cold_key = "tpknam1qyp99zaaza25j6yq9yrxu657ayy5qfwma3qat4gdemnrwhj0mdegkgq4fa4yn"

[validator_account.metadata]
email = "validator2@gmail.com"
[[validator_account]]
address = "tnam1q8378h06dkpdzq9krsrs3sw7lcxfmery4y6g8udy"
vp = "vp_user"
commission_rate = "0.05"
max_commission_rate_change = "0.01"
net_address = "127.0.0.1:28657"
consensus_key = "tpknam1qpggrw92cey8rtwcm59zpe557t2n9wzzxwn4fd9hz4fpsqt65lrggmpk2qm"
protocol_key = "tpknam1qzv7x635yhfrvp339j30myxz8vsvrn4qg0zpdg0280z4uuqmvc85jgfu2kf"
tendermint_node_key = "tpknam1qqttqvf6ruaf5zeelvc7cltgyzcjm2yamtlxcedp7vumxugmsnmhv2f9e0j"
eth_hot_key = "tpknam1qyp06r4hq40qs0ashkw9qpq23kfkcdc6nulwwuh8cwfumht2syzy6eqrujn75"
eth_cold_key = "tpknam1qyp3r6dpwtw8emker7u979ks556w9rdmyc337lkur0kah2nru8zud9gpr9prr"

[validator_account.metadata]
email = "validator1@gmail.com"
[[bond]]
source = "tnam1qyqxdjexcs8lpr24r6u96e4387rfa4zzsu7vvymm"
validator = "tnam1qyqxdjexcs8lpr24r6u96e4387rfa4zzsu7vvymm"
amount = "1000"

[[bond]]
source = "tnam1q8378h06dkpdzq9krsrs3sw7lcxfmery4y6g8udy"
validator = "tnam1q8378h06dkpdzq9krsrs3sw7lcxfmery4y6g8udy"
amount = "1000"

