[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_vm_env"
resolver = "2"
version = "0.7.0"

[features]
default = []

[dependencies]
namada = {path = "../shared"}
borsh = "0.9.0"
