[package]
authors = ["Heliax <TODO@heliax.dev>"]
edition = "2018"
name = "anoma_vm_env"
version = "0.1.0"

[dependencies]
anoma_shared = {path = "../shared"}
anoma_vm_macro = {path = "../vm_macro"}
borsh = "0.8.2"
