[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2018"
license = "GPL-3.0"
name = "anoma_vm_env"
resolver = "2"
version = "0.2.0"

[features]
ABCI = [
    "anoma/ABCI",
]

ABCI-plus-plus = [
    "anoma/ABCI-plus-plus",
]

[dependencies]
anoma = {path = "../shared"}
anoma_vm_macro = {path = "../vm_macro"}
borsh = "0.9.0"
