[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_vm_env"
resolver = "2"
version = "0.13.3"

[features]
default = ["abciplus"]
abciplus = [
  "namada_core/abciplus",
]

[dependencies]
namada_core = {path = "../core", default-features = false}
borsh = "0.9.0"
masp_primitives = { git = "https://github.com/anoma/masp", branch = "murisi/namada-integration" }
masp_proofs = { git = "https://github.com/anoma/masp", branch = "murisi/namada-integration" }
hex = "0.4.3"
