[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2021"
license = "GPL-3.0"
name = "namada_vm_env"
resolver = "2"
version = "0.15.1"

[features]
default = ["abciplus"]
abciplus = [
  "namada_core/abciplus",
]

[dependencies]
namada_core = {path = "../core", default-features = false}
borsh = "0.9.0"
# branch = "murisi/namada-integration"
masp_primitives = { git = "https://github.com/anoma/masp", rev = "1ed99e86d8795a363df170042089283ea9a43d93" }
masp_proofs = { git = "https://github.com/anoma/masp", rev = "1ed99e86d8795a363df170042089283ea9a43d93" }
hex = "0.4.3"
