[package]
name = "namada_light_sdk"
description = "A higher level, user friendly version of the Namada SDK"
resolver = "2"
authors.workspace = true
edition.workspace = true
documentation.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
namada_sdk = { path = "../sdk" }

borsh.workspace = true
borsh-ext.workspace = true
prost.workspace = true
tendermint-config.workspace = true
tendermint-rpc = { workspace = true, features = ["http-client"] }
tokio = {workspace = true, features = ["rt"]}
serde_json = "1.0.108"
