[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2018"
license = "GPL-3.0"
name = "anoma_shared"
resolver = "2"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
# for integration tests and test utilies
testing = []
wasm-runtime = [
  "wasmer",
  "wasmer-compiler-singlepass",
  "wasmer-engine-jit",
  "parity-wasm",
  "pwasm-utils",
]

[dependencies]
bech32 = "0.8.0"
borsh = "0.9.0"
ed25519-dalek = {version = "1.0.1", default-features = false, features = ["rand", "u64_backend", "serde"]}
itertools = "0.10.0"
parity-wasm = {version = "0.42.2", optional = true}
pwasm-utils = {version = "0.18.0", optional = true}
serde = {version = "1.0.125", features = ["derive"]}
sha2 = "0.9.3"
# We switch off "blake2b" because it cannot be compiled to wasm
sparse-merkle-tree = {git = "https://github.com/heliaxdev/sparse-merkle-tree", branch = "tomas/encoding-0.9.0b", default-features = false, features = ["std", "borsh"]}
thiserror = "1.0.24"
tracing = "0.1.26"
wasmer = {version = "1.0.2", optional = true}
wasmer-compiler-singlepass = {version = "1.0.2", optional = true}
wasmer-engine-jit = {version = "1.0.2", optional = true}
wasmparser = "0.78.2"

[dev-dependencies]
proptest = "1.0.0"
wasmer-vm = "1.0.2"
# TODO the older versions of rand and rand_core are currently required to avoid mismatching version issue (https://github.com/dalek-cryptography/ed25519-dalek/pull/159)
rand = {version = "0.7"}
rand_core = {version = "0.5"}
