[package]
authors = ["Heliax AG <hello@heliax.dev>"]
edition = "2018"
license = "GPL-3.0"
name = "anoma_shared"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for integration tests and test utilies
testing = []

[dependencies]
bech32 = "0.8.0"
borsh = "0.8.1"
ed25519-dalek = {version = "1.0.1", default-features = false, features = ["rand", "u64_backend", "serde"]}
serde = {version = "1.0.125", features = ["derive"]}
sha2 = "0.9.3"
# We switch off "blake2b" because it cannot be compiled to wasm
sparse-merkle-tree = {git = "https://github.com/heliaxdev/sparse-merkle-tree", branch = "tomas/encoding", default-features = false, features = ["std", "with_borsh"]}
thiserror = "1.0.24"
tracing = "0.1.26"

[dev-dependencies]
proptest = "1.0.0"
rand = "0.8.3"
