name: Anoma CI

on:
  pull_request:
    types: [review_requested, ready_for_review]
    branches:
      - master

jobs:
  build:
    name: Build Anoma
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ledger

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/anoma-prototype/ledger/vp_template
            ~/anoma-prototype/ledger/tx_template
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cargo-
      - name: Run requirements
        run: |
              make -C ../tx_template deps
              make build-wasm-scripts   
      - name: Run build
        run: make build
      - name: Run test
        run: make test

  format:
    name: Format Anoma
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ledger

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-03-09
          components: rustfmt
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ../vp_template
            ../tx_template
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-key: cargo-
      - name: Run fmt
        run: make fmt-check

  lint:
    name: Lint Anoma
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ledger

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ../vp_template
            ../tx_template
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-key: cargo-
      - name: Run clippy
        run: make clippy-check