name: Anoma CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build Anoma
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/work/anoma-prototype/anoma-prototype/tx_template
            ~/work/anoma-prototype/anoma-prototype/vp_template
            ~/work/anoma-prototype/anoma-prototype/ledger/target
          key: cache-v4-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cache-v4-cargo- 
      - name: Run requirements
        run: |
              make -C ../tx_template deps
              make build-wasm-scripts
        working-directory: ledger
      - name: Run build
        run: make build
        working-directory: ledger
      - name: Run clippy
        run: make clippy-check
        working-directory: ledger
      - name: Run test
        run: make test
        working-directory: ledger

  format:
    if: github.event.pull_request.draft == false
    name: Format Anoma
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-03-09
          components: rustfmt
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/work/anoma-prototype/anoma-prototype/tx_template
            ~/work/anoma-prototype/anoma-prototype/vp_template
            ~/work/anoma-prototype/anoma-prototype/ledger/target
          key: cache-v4-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cache-v4-cargo- 
      - name: Run fmt
        run: make fmt-check
        working-directory: ledger