name: Anoma CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - master

jobs:
  build:
    if: github.event.pull_request.draft == false
    name: Build Anoma
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/work/anoma-prototype/anoma-prototype/matchmaker_template/target
            ~/work/anoma-prototype/anoma-prototype/txs/*/target
            ~/work/anoma-prototype/anoma-prototype/vps/*/target
            ~/work/anoma-prototype/anoma-prototype/target
          key: cache-v5-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cache-v5-cargo-
      - name: Run requirements
        run: |
              make -C txs/tx_template deps
              make build-wasm-scripts
      - name: Run build
        run: make build
      - name: Run test
        run: make test

  format:
    if: github.event.pull_request.draft == false
    name: Format and Lint Anoma
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          # This should match the nightly version specified in the root Makefile
          toolchain: nightly-2021-03-09
          components: rustfmt, clippy
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/work/anoma-prototype/anoma-prototype/matchmaker_template/target
            ~/work/anoma-prototype/anoma-prototype/txs/*/target
            ~/work/anoma-prototype/anoma-prototype/vps/*/target
            ~/work/anoma-prototype/anoma-prototype/target
          # The key has to be different from build as rustfmt and clippy don't 
          # share the same build artifacts 
          key: cache-v5-lint-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cache-v5-lint-
      - name: Run fmt
        run: make fmt-check
      - name: Run clippy
        run: make clippy-check