name: Anoma CI

on:
  pull_request:
    # types: [review_requested, ready_for_review]
    types: [synchronize]
    branches:
      - master

jobs:
  build:
    name: Build Anoma
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/anoma-prototype/tx_template
            ~/anoma-prototype/vp_template
            ~/anoma-prototype/ledger/target
          key: cache-v2-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cache-v2-cargo-
      - name: Debug
        run: |
              cd ~
              pwd
              ls
              cd runner
              ls
              echo "---"
              ls ~/.cargo/registry
              du -hs ~/.cargo/registry
              echo "---"
              ls ~/.cargo/git
              du -hs ~/.cargo/git
              echo "---"
              ls ~/anoma-prototype
              echo "---"
              ls ~/anoma-prototype/ledger   
      - name: Run requirements
        run: |
              make -C ../tx_template deps
              make build-wasm-scripts
        working-directory: ledger
      - name: Debug2
        run: |
              ls ~/anoma-prototype/tx_template
              echo "---"
              ls ~/anoma-prototype/vp_template
              echo "---"
              ls ~/anoma-prototype/ledger/target
      - name: Run build
        run: make build
        working-directory: ledger
      - name: Run test
        run: make test
        working-directory: ledger

  format:
    name: Format Anoma
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ledger

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-03-09
          components: rustfmt
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ../vp_template
            ../tx_template
            target
          key: cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-key: cargo-
      - name: Run fmt
        run: make fmt-check
        working-directory: ledger

  lint:
    name: Lint Anoma
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ledger

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/anoma-prototype/ledger/target
          key: cache-v2-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: cache-v2-cargo-
      - name: Run clippy
        run: make clippy-check
        working-directory: ledger