name: github pages

on:
  push:
    branches:
      - master

env:
  CARGO_INCREMENTAL: 0

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - uses: Swatinem/rust-cache@v1
      - run: | 
          rustup component add rustfmt
          make -C tech-specs dev-deps
          make build-doc
          mkdir tech-specs/book/rustdoc
          mv -v target/doc/* tech-specs/book/rustdoc/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./tech-specs/book
